In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
X,y = load_iris(return_X_y=True)

In [3]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2)

Scaling using Standard Scaler

In [4]:
scaler= StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Using MinMax Scaler

In [5]:
from sklearn.preprocessing import MinMaxScaler

scaler= MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled= scaler.transform(X_test)

Using RobustScaler

In [6]:
from sklearn.preprocessing import RobustScaler

scaler= RobustScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

ENCODING

In [7]:
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

In [8]:
data=fetch_openml('car',as_frame=True).frame

C:\Users\vaishnavi\AppData\Roaming\Python\Python313\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)

In [9]:
data.sample(10)

     buying  maint doors persons lug_boot safety binaryClass
1200    med    low     2       4      med    low           P
1036    med   high     4       4    small    med           P
1208    med    low     2    more    small   high           P
1101    med    med     2    more      med    low           P
975     med   high     2       2      med    low           P
117   vhigh   high     2       4    small    low           P
1126    med    med     3    more    small    med           N
712    high    med     4       4    small    med           P
916     med  vhigh     3    more      big    med           N
896     med  vhigh     3       2      med   high           P

Ordinal Encoder

In [10]:
columns_to_encode=['lug_boot','safety','buying']

encoder=OrdinalEncoder(categories=[['small','med','big'],
                       ['low','med','high'],
                       ['low','med','high','vhigh']
                       ]
                       )
data[columns_to_encode]=encoder.fit_transform(data[columns_to_encode])

In [11]:
maint_coln=OrdinalEncoder(categories=[['low','med','high','vhigh']])
data['maint']=maint_coln.fit_transform(data[['maint']])

In [12]:
data['doors']=data['doors'].replace('5more',5).astype(int)
data['persons']=data['persons'].replace('more',5).astype(int)

C:\Users\vaishnavi\AppData\Local\Temp\ipykernel_22960\1196710813.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  data['doors']=data['doors'].replace('5more',5).astype(int)
C:\Users\vaishnavi\AppData\Local\Temp\ipykernel_22960\1196710813.py:2: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  data['persons']=data['persons'].replace('more',5).astype(int)

In [13]:
data=fetch_openml('adult',as_frame=True).frame

C:\Users\vaishnavi\AppData\Roaming\Python\Python313\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)

One hot Encoding

In [14]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [15]:
coln_to_encode=OneHotEncoder(handle_unknown='ignore',sparse_output=False)

encode_value=coln_to_encode.fit_transform(data[['occupation','race','relationship']])

new_coln=coln_to_encode.get_feature_names_out(['occupation','race','relationship'])

encode_df=pd.DataFrame(encode_value,columns=new_coln)

data=pd.concat([data,encode_df],axis=1)

data=data.drop(columns=['occupation','race','relationship'])

In [16]:
ohot=OneHotEncoder(handle_unknown='ignore',sparse_output=False)

encode_value=ohot.fit_transform(data[['workclass','education']])

new_coln=ohot.get_feature_names_out(['workclass','education'])

encoded_df=pd.DataFrame(encode_value,columns=new_coln)

data=pd.concat([data,encode_df],axis=1)

data=data.drop(columns=['workclass','education'])

In [17]:
data

,age,fnlwgt,education-num,marital-status,sex,capitalgain,capitalloss,hoursperweek,native-country,class,...,race_Asian-Pac-Islander,race_Black,race_Other,race_White,relationship_Husband,relationship_Not-in-family,relationship_Other-relative,relationship_Own-child,relationship_Unmarried,relationship_Wife
0,2,77516,13,Never-married,Male,1,0,2,United-States,<=50K,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1,3,83311,13,Married-civ-spouse,Male,0,0,0,United-States,<=50K,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
2,2,215646,9,Divorced,Male,0,0,2,United-States,<=50K,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,3,234721,7,Married-civ-spouse,Male,0,0,2,United-States,<=50K,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1,338409,13,Married-civ-spouse,Female,0,0,2,Cuba,<=50K,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,215419,13,Divorced,Female,0,0,2,United-States,<=50K,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
48838,4,321403,9,Widowed,Male,0,0,2,United-States,<=50K,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
48839,2,374983,13,Married-civ-spouse,Male,0,0,3,United-States,<=50K,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
48840,2,83891,13,Divorced,Male,2,0,2,United-States,<=50K,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
48841,1,182148,13,Married-civ-spouse,Male,0,0,3,United-States,>50K,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0